path: C:\chess_dataset_1 - Copy (2)
train: images
val: images

names:
  0: chess_board
  1: white_rook
  2: white_bishop
  3: white_queen
  4: white_king
  5: white_knight
  6: white_pawn
  7: black_rook
  8: black_bishop
  9: black_queen
  10: black_king
  11: black_knight
  12: black_pawn


# Hyperparameters ------------------------------------------------------------------------------------------------------
# lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
# lrf: 0.01  # final learning rate (lr0 * lrf)
# momentum: 0.937  # SGD momentum/Adam beta1
# weight_decay: 0.0005  # optimizer weight decay 5e-4
# warmup_epochs: 3.0  # warmup epochs (fractions ok)
# warmup_momentum: 0.8  # warmup initial momentum
# warmup_bias_lr: 0.1  # warmup initial bias lr
# box: 7.5  # box loss gain
# cls: 0.5  # cls loss gain (scale with pixels)
# dfl: 1.5  # dfl loss gain
# pose: 12.0  # pose loss gain
# kobj: 1.0  # keypoint obj loss gain
# label_smoothing: 0.0  # label smoothing (fraction)
# nbs: 64  # nominal batch size
#hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
## hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
## hsv_v: 0.4  # image HSV-Value augmentation (fraction)
## degrees: 0.0  # image rotation (+/- deg)
#translate: 0.3  # image translation (+/- fraction)
#scale: 0.5  # image scale (+/- gain)
#shear: 0.2  # image shear (+/- deg) from -0.5 to 0.5
#perspective: 0.1  # image perspective (+/- fraction), range 0-0.001
#flipud: 0.7  # image flip up-down (probability)
#fliplr: 0.5  # image flip left-right (probability)
#mosaic: 0.3  # image mosaic (probability)
#mixup: 0.3  # image mixup (probability)
#copy_paste: 0.5  # segment copy-paste (probability)